# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy development

on:
  push:
    branches: [ development ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          always-auth: true
          registry-url: https://npm.pkg.github.com/

      - name: Install Packages
        run: yarn install

      - name: Build Dev
        run: yarn build:dev
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: cn-northwest-1

      - name: Clean S3 bucket
          aws s3 rm s3://angular-dev.dxsuite.cn --recursive

      - name: Sync web files
        run: |
          aws s3 cp dist/dxsuite-ng-admin/ s3://angular-dev.dxsuite.cn --recursive

      - name: Clear CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id EROYVGDKIVRMO --paths "/*"
          