# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DEPLOY DEVELOPMENT

on:
  push:
    branches: [development]
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          always-auth: true
          registry-url: https://npm.pkg.github.com/

      - name: Install Packages
        run: yarn install

      - name: Build
        run: yarn build:dev
      
      - name: Release
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCP_HOST_DEV }}
          username: ${{ secrets.SCP_USERNAME_DEV }}
          password: ${{ secrets.SCP_PASSWORD_DEV }}
          port: ${{ secrets.SCP_PORT_DEV }}
          source: "dist/dxsuite-ng-admin/"
          target: "/var/apps/dxsuite-ng"
          strip_components: 2
  


